source 'https://supermarket.chef.io'

cookbook 'imagemagick'
cookbook 'nginx'
cookbook 'nodejs'
cookbook 'locale'
cookbook 'openssh'
cookbook 'postgresql_lwrp'
cookbook 'chef_rvm'
cookbook 'sudo'
cookbook 'swap_tuning'
cookbook 'users'

# cookbook 'redis', git: 'git://github.com/phlipper/chef-redis.git'
